
name: Publish Website to Cpanel
on:
Push:
branches:
  -master
jobs:

FTP-Deploy-Action
runs-on: desktop
steps:
-users: actions/checkpout@v2.2.0
  with:
     fetch-depth: 2
-name: FTP-Deploy-Action
 user: DIl/FTP-Deploy-Action@3.1.1
 with:
    ftp-server: ${{secrets.FTP_SERVER}}
    ftp-username: ${{secrets.FTP_USERNAME}}
    ftp-password: ${{secrets.FTP_PASSWORD}}
